language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "node"

install:
  - npm i -g gulp
  - npm i -g webpack
  - npm i

script:
  - npm run build
  - npm run lint

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
